version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-8000}:80'
        volumes:
            - '.:/var/www/html'
            - './docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf'
        networks:
            - platform


networks:
    platform:
        driver: bridge
