<?php

namespace App;

class CountryCities
{
    public function get()
    {
        return collect($this->data())
            ->map(fn($item, $key) => ['id' => $key, ...$item]);
    }

    private function data()
    {
        return [
            ['country' => "Afghanistan", "city" => "Kabul"],
            ['country' => "Albania", "city" => "Tirana (Tirane)"],
            ['country' => "Algeria", "city" => "Algiers"],
            ['country' => "Andorra", "city" => "Andorra la Vella"],
            ['country' => "Angola", "city" => "Luanda"],
            ['country' => "Antigua and Barbuda", "city" => "Saint John's"],
            ['country' => "Argentina", "city" => "Buenos Aires"],
            ['country' => "Armenia", "city" => "Yerevan"],
            ['country' => "Australia", "city" => "Canberra"],
            ['country' => "Austria", "city" => "Vienna"],
            ['country' => "Azerbaijan", "city" => "Baku"],
            ['country' => "Bahamas", "city" => "Nassau"],
            ['country' => "Bahrain", "city" => "Manama"],
            ['country' => "Bangladesh", "city" => "Dhaka"],
            ['country' => "Barbados", "city" => "Bridgetown"],
            ['country' => "Belarus", "city" => "Minsk"],
            ['country' => "Belgium", "city" => "Brussels"],
            ['country' => "Belize", "city" => "Belmopan"],
            ['country' => "Benin", "city" => "Porto Novo"],
            ['country' => "Bhutan", "city" => "Thimphu"],
            ['country' => "Bolivia", "city" => "La Paz (administrative), Sucre (official)"],
            ['country' => "Bosnia and Herzegovina", "city" => "Sarajevo"],
            ['country' => "Botswana", "city" => "Gaborone"],
            ['country' => "Brazil", "city" => "Brasilia"],
            ['country' => "Brunei", "city" => "Bandar Seri Begawan"],
            ['country' => "Bulgaria", "city" => "Sofia"],
            ['country' => "Burkina Faso", "city" => "Ouagadougou"],
            ['country' => "Burundi", "city" => "Gitega"],
            ['country' => "Cambodia", "city" => "Phnom Penh"],
            ['country' => "Cameroon", "city" => "Yaounde"],
            ['country' => "Canada", "city" => "Ottawa"],
            ['country' => "Cape Verde", "city" => "Praia"],
            ['country' => "Central African Republic", "city" => "Bangui"],
            ['country' => "Chad", "city" => "N'Djamena"],
            ['country' => "Chile", "city" => "Santiago"],
            ['country' => "China", "city" => "Beijing"],
            ['country' => "Colombia", "city" => "Bogota"],
            ['country' => "Comoros", "city" => "Moroni"],
            ['country' => "Congo, Democratic Republic of the", "city" => "Kinshasa"],
            ['country' => "Congo, Republic of the", "city" => "Brazzaville"],
            ['country' => "Costa Rica", "city" => "San Jose"],
            ['country' => "Côte d'Ivoire (Ivory Coast)", "city" => "Yamoussoukro[4]"],
            ['country' => "Croatia", "city" => "Zagreb"],
            ['country' => "Cuba", "city" => "Havana"],
            ['country' => "Cyprus", "city" => "Nicosia"],
            ['country' => "Czech Republic (Czechia)", "city" => "Prague"],
            ['country' => "Denmark", "city" => "Copenhagen"],
            ['country' => "Djibouti", "city" => "Djibouti"],
            ['country' => "Dominica", "city" => "Roseau"],
            ['country' => "Dominican Republic", "city" => "Santo Domingo"],
            ['country' => "East Timor", "city" => "Dili"],
            ['country' => "Ecuador", "city" => "Quito"],
            ['country' => "Egypt", "city" => "Cairo"],
            ['country' => "El Salvador", "city" => "San Salvador"],
            ['country' => "England", "city" => "London"],
            ['country' => "Equatorial Guinea", "city" => "Malabo"],
            ['country' => "Eritrea", "city" => "Asmara"],
            ['country' => "Estonia", "city" => "Tallinn"],
            ['country' => "Eswatini (Swaziland)", "city" => "Mbabana"],
            ['country' => "Ethiopia", "city" => "Addis Ababa"],
            ['country' => "Federated States of Micronesia", "city" => "Palikir"],
            ['country' => "Fiji", "city" => "Suva"],
            ['country' => "Finland", "city" => "Helsinki"],
            ['country' => "France", "city" => "Paris"],
            ['country' => "Gabon", "city" => "Libreville"],
            ['country' => "Gambia", "city" => "Banjul"],
            ['country' => "Georgia", "city" => "Tbilisi"],
            ['country' => "Germany", "city" => "Berlin"],
            ['country' => "Ghana", "city" => "Accra"],
            ['country' => "Greece", "city" => "Athens"],
            ['country' => "Grenada", "city" => "Saint George's"],
            ['country' => "Guatemala", "city" => "Guatemala City"],
            ['country' => "Guinea", "city" => "Conakry"],
            ['country' => "Guinea-Bissau", "city" => "Bissau"],
            ['country' => "Guyana", "city" => "Georgetown"],
            ['country' => "Haiti", "city" => "Port au Prince"],
            ['country' => "Honduras", "city" => "Tegucigalpa"],
            ['country' => "Hungary", "city" => "Budapest"],
            ['country' => "Iceland", "city" => "Reykjavik"],
            ['country' => "India", "city" => "New Delhi"],
            ['country' => "Indonesia", "city" => "Jakarta"],
            ['country' => "Iran", "city" => "Tehran"],
            ['country' => "Iraq", "city" => "Baghdad"],
            ['country' => "Ireland", "city" => "Dublin"],
            ['country' => "Israel", "city" => "Jerusalem (very limited international recognition)"],
            ['country' => "Italy", "city" => "Rome"],
            ['country' => "Jamaica", "city" => "Kingston"],
            ['country' => "Japan", "city" => "Tokyo"],
            ['country' => "Jordan", "city" => "Amman"],
            ['country' => "Kazakhstan", "city" => "Nur-Sultan"],
            ['country' => "Kenya", "city" => "Nairobi"],
            ['country' => "Kiribati", "city" => "Tarawa Atoll"],
            ['country' => "Kosovo", "city" => "Pristina"],
            ['country' => "Kuwait", "city" => "Kuwait City"],
            ['country' => "Kyrgyzstan", "city" => "Bishkek"],
            ['country' => "Laos", "city" => "Vientiane"],
            ['country' => "Latvia", "city" => "Riga"],
            ['country' => "Lebanon", "city" => "Beirut"],
            ['country' => "Lesotho", "city" => "Maseru"],
            ['country' => "Liberia", "city" => "Monrovia"],
            ['country' => "Libya", "city" => "Tripoli"],
            ['country' => "Liechtenstein", "city" => "Vaduz"],
            ['country' => "Lithuania", "city" => "Vilnius"],
            ['country' => "Luxembourg", "city" => "Luxembourg"],
            ['country' => "Madagascar", "city" => "Antananarivo"],
            ['country' => "Malawi", "city" => "Lilongwe"],
            ['country' => "Malaysia", "city" => "Kuala Lumpur"],
            ['country' => "Maldives", "city" => "Male"],
            ['country' => "Mali", "city" => "Bamako"],
            ['country' => "Malta", "city" => "Valletta"],
            ['country' => "Marshall Islands", "city" => "Majuro"],
            ['country' => "Mauritania", "city" => "Nouakchott"],
            ['country' => "Mauritius", "city" => "Port Louis"],
            ['country' => "Mexico", "city" => "Mexico City"],
            ['country' => "Moldova", "city" => "Chisinau"],
            ['country' => "Monaco", "city" => "Monaco"],
            ['country' => "Mongolia", "city" => "Ulaanbaatar"],
            ['country' => "Montenegro", "city" => "Podgorica"],
            ['country' => "Morocco", "city" => "Rabat"],
            ['country' => "Mozambique", "city" => "Maputo"],
            ['country' => "Myanmar (Burma)", "city" => "Nay Pyi Taw"],
            ['country' => "Namibia", "city" => "Windhoek"],
            ['country' => "Nauru", "city" => "No official capital"],
            ['country' => "Nepal", "city" => "Kathmandu"],
            ['country' => "Netherlands", "city" => "Amsterdam"],
            ['country' => "New Zealand", "city" => "Wellington"],
            ['country' => "Nicaragua", "city" => "Managua"],
            ['country' => "Niger", "city" => "Niamey"],
            ['country' => "Nigeria", "city" => "Abuja"],
            ['country' => "North Korea", "city" => "Pyongyang"],
            ['country' => "North Macedonia (Macedonia)", "city" => "Skopje"],
            ['country' => "Northern Ireland", "city" => "Belfast"],
            ['country' => "Norway", "city" => "Oslo"],
            ['country' => "Oman", "city" => "Muscat"],
            ['country' => "Pakistan", "city" => "Islamabad"],
            ['country' => "Palau", "city" => "Melekeok"],
            ['country' => "Panama", "city" => "Panama City"],
            ['country' => "Papua New Guinea", "city" => "Port Moresby"],
            ['country' => "Paraguay", "city" => "Asuncion"],
            ['country' => "Peru", "city" => "Lima"],
            ['country' => "Philippines", "city" => "Manila"],
            ['country' => "Poland", "city" => "Warsaw"],
            ['country' => "Portugal", "city" => "Lisbon"],
            ['country' => "Qatar", "city" => "Doha"],
            ['country' => "Romania", "city" => "Bucharest"],
            ['country' => "Russia", "city" => "Moscow"],
            ['country' => "Rwanda", "city" => "Kigali"],
            ['country' => "Saint Kitts and Nevis", "city" => "Basseterre"],
            ['country' => "Saint Lucia", "city" => "Castries"],
            ['country' => "Saint Vincent and the Grenadines", "city" => "Kingstown"],
            ['country' => "Samoa", "city" => "Apia"],
            ['country' => "San Marino", "city" => "San Marino"],
            ['country' => "Sao Tome and Principe", "city" => "Sao Tome"],
            ['country' => "Saudi Arabia", "city" => "Riyadh"],
            ['country' => "Scotland", "city" => "Edinburgh"],
            ['country' => "Senegal", "city" => "Dakar"],
            ['country' => "Serbia", "city" => "Belgrade"],
            ['country' => "Seychelles", "city" => "Victoria"],
            ['country' => "Sierra Leone", "city" => "Freetown"],
            ['country' => "Singapore", "city" => "Singapore"],
            ['country' => "Slovakia", "city" => "Bratislava"],
            ['country' => "Slovenia", "city" => "Ljubljana"],
            ['country' => "Solomon Islands", "city" => "Honiara"],
            ['country' => "Somalia", "city" => "Mogadishu"],
            ['country' => "South Africa", "city" => "Pretoria, Bloemfontein, Cape Town"],
            ['country' => "South Korea", "city" => "Seoul"],
            ['country' => "South Sudan", "city" => "Juba"],
            ['country' => "Spain", "city" => "Madrid"],
            ['country' => "Sri Lanka", "city" => "Colombo"],
            ['country' => "Sudan", "city" => "Khartoum"],
            ['country' => "Suriname", "city" => "Paramaribo"],
            ['country' => "Sweden", "city" => "Stockholm"],
            ['country' => "Switzerland", "city" => "Bern"],
            ['country' => "Syria", "city" => "Damascus"],
            ['country' => "Taiwan", "city" => "Taipei"],
            ['country' => "Tajikistan", "city" => "Dushanbe"],
            ['country' => "Tanzania", "city" => "Dodoma"],
            ['country' => "Thailand", "city" => "Bangkok"],
            ['country' => "Togo", "city" => "Lome"],
            ['country' => "Tonga", "city" => "Nuku'alofa"],
            ['country' => "Trinidad and Tobago", "city" => "Port of Spain"],
            ['country' => "Tunisia", "city" => "Tunis"],
            ['country' => "Turkey", "city" => "Ankara"],
            ['country' => "Turkmenistan", "city" => "Ashgabat"],
            ['country' => "Tuvalu", "city" => "Funafuti"],
            ['country' => "Uganda", "city" => "Kampala"],
            ['country' => "Ukraine", "city" => "Kiev"],
            ['country' => "United Arab Emirates", "city" => "Abu Dhabi"],
            ['country' => "United Kingdom", "city" => "London"],
            ['country' => "United States", "city" => "Washington D.C."],
            ['country' => "Uruguay", "city" => "Montevideo"],
            ['country' => "Uzbekistan", "city" => "Tashkent"],
            ['country' => "Vanuatu", "city" => "Port Vila"],
            ['country' => "Vatican City", "city" => "Vatican City"],
            ['country' => "Venezuela", "city" => "Caracas"],
            ['country' => "Vietnam", "city" => "Hanoi"],
            ['country' => "Wales", "city" => "Cardiff"],
            ['country' => "Yemen", "city" => "Sana'a"],
            ['country' => "Zambia", "city" => "Lusaka"],
            ['country' => "Zimbabwe", "city" => "Harare"],
        ];
    }
}
